import { jsx as _jsx } from "react/jsx-runtime";
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { BrowserRouter } from "react-router-dom";
import App from "./App";
import { AuthProvider } from "./hooks/useAuth";
import { ErrorBoundary } from "./components/layout/ErrorBoundary";
import { installGlobalErrorReporting } from "./lib/report-error";
import "./styles/globals.css";
installGlobalErrorReporting();
createRoot(document.getElementById("root")).render(_jsx(StrictMode, { children: _jsx(ErrorBoundary, { children: _jsx(BrowserRouter, { children: _jsx(AuthProvider, { children: _jsx(App, {}) }) }) }) }));
